// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  heading: defineAsyncComponent(() => import("./Heading/index.vue")),
  image: defineAsyncComponent(() => import("./Image/index.vue")),
  recent_list: defineAsyncComponent(() => import("./RecentList/index.vue")),
  text: defineAsyncComponent(() => import("./Text/index.vue")),
});
